# Generated by Django 3.1 on 2020-10-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Uknown', max_length=100)),
                ('email_id', models.EmailField(default='example@gmail.com', max_length=254)),
                ('mobile_number', models.BigIntegerField(default=0)),
                ('gender', models.CharField(default='None', max_length=100)),
                ('password', models.CharField(default='******', max_length=12)),
            ],
        ),
    ]
