# Generated by Django 3.1 on 2020-10-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin_profile',
            table='admin_profile',
        ),
    ]
