# Generated by Django 3.1 on 2020-10-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_auto_20201004_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='Uknown', max_length=100)),
                ('ad_active_time', models.IntegerField(default=0)),
                ('dedicated_chat', models.BooleanField(default=False)),
                ('dedicated_phone', models.BooleanField(default=False)),
                ('number_of_ad_month', models.IntegerField(default=0)),
                ('commision_less_5_lack', models.IntegerField(default=0)),
                ('commision_less_20_lack', models.IntegerField(default=0)),
                ('commision_more_20_lack', models.IntegerField(default=0)),
                ('commision_less_1_core', models.IntegerField(default=0)),
                ('monthly_price', models.BigIntegerField(default=0.0)),
                ('service_charge', models.BigIntegerField(default=0.0)),
            ],
        ),
    ]
