# Generated by Django 3.1 on 2020-10-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_subscription_plans'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription_plans',
            table='subscription_plans',
        ),
    ]
