# Generated by Django 3.1 on 2020-10-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_auto_20201010_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_plans',
            old_name='commision_less_1_core',
            new_name='commision_less_25_lack',
        ),
        migrations.RenameField(
            model_name='subscription_plans',
            old_name='commision_less_20_lack',
            new_name='commision_more_25_lack',
        ),
        migrations.RenameField(
            model_name='subscription_plans',
            old_name='commision_less_5_lack',
            new_name='commision_more_50_lack',
        ),
        migrations.RemoveField(
            model_name='subscription_plans',
            name='commision_more_20_lack',
        ),
    ]
