# Generated by Django 3.1 on 2020-10-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_auto_20201012_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plans',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
