# Generated by Django 3.1 on 2020-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_subscription_plans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plans',
            name='number_of_image_per_ads',
            field=models.IntegerField(default=0),
        ),
    ]
