# Generated by Django 3.1 on 2020-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Uknown', max_length=100)),
                ('email_id', models.EmailField(default='example@gmail.com', max_length=254)),
                ('mobile_number', models.BigIntegerField(default=0)),
                ('password', models.CharField(default='******', max_length=12)),
            ],
            options={
                'db_table': 'user_login',
            },
        ),
    ]
