# Generated by Django 3.1 on 2020-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(default='Uknown', max_length=100)),
                ('pin_code', models.BigIntegerField(default=0)),
                ('address', models.TextField(default='Uknown')),
                ('near_by', models.TextField(default='Uknown')),
            ],
            options={
                'db_table': 'location_details',
            },
        ),
        migrations.CreateModel(
            name='property_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_type', models.CharField(default='Uknown', max_length=100)),
                ('bhk_type', models.CharField(default='Uknown', max_length=100)),
                ('ownership', models.CharField(default='Uknown', max_length=100)),
                ('built_up_area', models.BigIntegerField(default=0)),
                ('property_age', models.CharField(default='Uknown', max_length=100)),
                ('facing', models.CharField(default='Uknown', max_length=100)),
                ('floor_type', models.CharField(default='Uknown', max_length=100)),
                ('floor', models.CharField(default='Uknown', max_length=100)),
                ('total_floor', models.CharField(default='Uknown', max_length=100)),
            ],
            options={
                'db_table': 'Property_Details',
            },
        ),
        migrations.CreateModel(
            name='resale_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_price', models.BigIntegerField(default=0)),
                ('maintenance_cost', models.BigIntegerField(default=0)),
                ('available_from', models.CharField(default='00-00-0000', max_length=100)),
                ('kitchen_type', models.CharField(default='Uknown', max_length=100)),
                ('furnishining', models.CharField(default='Uknown', max_length=100)),
                ('parking', models.CharField(default='Uknown', max_length=100)),
                ('description', models.TextField(default='Uknown')),
            ],
            options={
                'db_table': 'resale_details',
            },
        ),
    ]
