# Generated by Django 3.1 on 2020-10-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_location_details_property_details_resale_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_details',
            name='property_id',
            field=models.IntegerField(default=0),
        ),
    ]
