# Generated by Django 3.1 on 2020-10-20 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_location_details_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property_details',
            name='user_id',
            field=models.CharField(default='Uknown', max_length=100),
        ),
    ]
