# Generated by Django 3.1 on 2020-10-20 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20201020_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
