# Generated by Django 3.1 on 2020-10-20 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20201020_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='additional_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(default=0)),
                ('i_want_to_get_my_property_painted', models.CharField(default='Uknown', max_length=200)),
                ('i_want_to_get_my_property_cleaned', models.CharField(default='Uknown', max_length=200)),
                ('do_you_have_all_document', models.CharField(default='Uknown', max_length=200)),
                ('have_you_paid_property_tax', models.CharField(default='Uknown', max_length=200)),
            ],
            options={
                'db_table': 'additional_information',
            },
        ),
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('balcony', models.IntegerField(default=0)),
                ('water_supply', models.CharField(default='Uknown', max_length=100)),
                ('gym', models.CharField(default='Uknown', max_length=100)),
                ('power_backup', models.CharField(default='Uknown', max_length=100)),
                ('gated_security', models.CharField(default='Uknown', max_length=100)),
                ('who_will_show_the_house', models.CharField(default='Uknown', max_length=100)),
                ('secondry_number', models.BigIntegerField(default=0)),
                ('club_house', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('children_Play_area', models.BooleanField(default=False)),
                ('intercom', models.BooleanField(default=False)),
                ('shoping_center', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('gas_pipeline', models.BooleanField(default=False)),
                ('internet_provider', models.BooleanField(default=False)),
                ('fire_safety', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(default=0)),
                ('availablity', models.CharField(default='Uknown', max_length=200)),
                ('start_time', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('end_time', models.TimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.AddField(
            model_name='resale_details',
            name='property_id',
            field=models.IntegerField(default=0),
        ),
    ]
