# Generated by Django 3.1 on 2020-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20201020_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='children_Play_area',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='club_house',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='fire_safety',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='gas_pipeline',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='intercom',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='internet_provider',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='lift',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='park',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='security',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='shoping_center',
            field=models.CharField(default='false', max_length=100),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='swimming_pool',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
