# Generated by Django 3.1 on 2020-10-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20201020_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='subscription_id',
            field=models.IntegerField(default=0),
        ),
    ]
